- app/views/shared/_footer.html.erb
> fix: Update year in copyright section of footer

- app/javascript/stylesheets/bootstrap-slider.min.css
- app/javascript/stylesheets/partials/_dark.scss
- app/javascript/stylesheets/partials/_player.scss
- app/javascript/stylesheets/partials/_surah-actions.scss
- app/javascript/stylesheets/select2-cust.scss
- app/views/chapters/_player.html.erb
- app/views/chapters/_surah_actions.html.erb
- app/views/chapters/_verse.html.erb
- config/database.yml
Fixed surrah action header issue 
fixed color in night mode 
fixed the play pause btn
> Changes playerbar

- app/javascript/stylesheets/partials/_surah-actions.scss
- app/javascript/stylesheets/select2-cust.scss
- app/views/chapters/_surah_actions.html.erb
- app/views/chapters/_verse.html.erb
Fixed surrah header tooltip, translation and remove button also align the play button in verse
> Fixed surrah header 

- app/views/shared/_footer.html.erb
@naveed-ahmad Closes issue #79
> fix: use sentence casing and one transliteration of Surah name in footer

- app/views/pages/donations.html.erb
> fix: correct grammar on donations page

- README.md
> fix(README): tidy up README, improving grammar and conciseness

- app/controllers/chapters_controller.rb
- app/presenters/ayatul_kursi_presenter.rb
- app/views/shared/_search_form.html.erb
@naveed-ahmad Ayatul Kursi Presenter had an additional `r` at the end
> fix(Presenter): correctly name Ayatual Kursi presenter

- .editorconfig
@naveed-ahmad Useful to have in projects
> Add .editorconfig file to standardise project

- README.md
@naveed-ahmad Apologies - this will be the last time sorting out the README
> docs: clean up README

- app/controllers/chapters_controller.rb
- app/javascript/controllers/chapter_controller.js
- app/javascript/controllers/slim_scroller_controller.js
- app/javascript/controllers/translation_controller.js
- app/javascript/packs/application.js
- app/javascript/slim-scroller/index.js
- app/javascript/stylesheets/partials/_player.scss
- app/presenters/chapter_presenter.rb
- app/views/chapters/_fonts.html.erb
- app/views/chapters/_player.html.erb
- app/views/chapters/_verses.html.erb
- app/views/chapters/load_verses.html.erb
- package.json
- yarn.lock
- We'll load all ayah and scroll to user's selected ayah
- Fixed slim scrolling plugin. Bundled it
> fixed jump to ayah

- app/controllers/search_controller.rb
- app/helpers/chapters_helper.rb
- app/javascript/controllers/search_form_controller.js
- app/javascript/stylesheets/partials/_search.scss
- app/presenters/search_presenter.rb
- app/views/chapters/_top_section.html.erb
- app/views/search/_suggestion.html.erb
- app/views/search/_verse.html.erb
- app/views/search/error.html.erb
- app/views/search/suggestion_error.html.erb
- config/initializers/elasticsearch.rb
- lib/search/results.rb
- Added placeholder for search & suggestion 
- Fixed ayah URLs( added translation ids)
> Search errors

- app/helpers/chapters_helper.rb
- app/javascript/controllers/chapter_controller.js
- app/javascript/controllers/verse_controller.js
- app/views/chapters/_verses.html.erb
- app/views/chapters/show.html.erb
- yarn.lock
This PR fixes the issue with the **reading mode** being changed to **translation mode** when the font of the page changes.
Also I started storing the state of which mode (active tab) the page is in now, so it can maintain the same state on changes.
> Fixed the reading mode issue

- README.md
@naveed-ahmad I have attempted to fix #204 
Icons are no more in **javascript** directory. Now they are in **assets** directory.
Let me know if it require more changes.
Best,
Hashir
> fixed src for images

- app/views/shared/_footer.html.erb
- app/views/shared/_left_side_bar.html.erb
Assalamu alaykom,
In the footer section, the link to salah.com points to sunnah.com . I did not know wheter I should change the link or the title so I kept both the links.
Please let me know if there is anything to change.
May Allah reward you for all your efforts
> [FIX] : update Salah.com link and add a link for Sunnah.com

- app/javascript/controllers/setting_controller.js
- app/javascript/stylesheets/pages/chapter.scss
- app/views/chapters/_fonts.html.erb
- app/views/settings/show.html.erb
and added upper and lower limits for the font size.
> Fixed text cut off for very big font sizes

- app/javascript/controllers/chapter_controller.js
- app/javascript/stylesheets/pages/chapter.scss
- app/javascript/stylesheets/partials/_search.scss
- app/views/search/_verse.html.erb
- app/views/search/search.html.erb
- config/locales/translation.ar.yml
- config/locales/translation.bn-BD.yml
- config/locales/translation.fa.yml
- config/locales/translation.fr.yml
- config/locales/translation.it.yml
- config/locales/translation.pt-BR.yml
- config/locales/translation.ur.yml
> Search fixes

- README.md
I noticed the shields on the README were not centered so I figured I'd center them and make this PR. Also changed the License shield description from MIT to GPL v3
> Center shields on README.md and update License Badge

- app/javascript/controllers/word_controller.js
This is to check if audio data is empty to avoid. 
Please review. Thanks.
> Checking the audio in data is empty or not before playing it. #280

- app/javascript/controllers/setting_controller.js
Update the chapter page with default translation.
> Refresh the chapter page when restting the default #234

- README.md
reported issue: https://github.com/quran/quran.com-frontend-v2/issues/301
> make ruby version in sync between README and Gemfile

- app/javascript/controllers/segment_player_controller.js
making segments array a sequential array
> fixes segment player

- README.md
With Discord there's no need to open an issue with one's e-mail to be able to join the Community.
> Fix Contact section in README.md
